name: fetch-prod
services:
  be:
    build: .
    ports:
      - 8000:8000
    environment:
      NODE_ENV: production
      PORT: 8000
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: fetch-be
      DB_PASSWORD: fetch-be
      DB_DATABASE: fetch
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: fetchrewards
      MYSQL_DATABASE: fetch
      MYSQL_USER: fetch-be
      MYSQL_PASSWORD: fetch-be
    volumes:
      - db_data:/var/lib/mysql:rw
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 30s
      retries: 10
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db_data:
