services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: fetchrewards
      MYSQL_DATABASE: fetch
      MYSQL_USER: fetch-be
      MYSQL_PASSWORD: fetch-be
    volumes:
      - db_data:/var/lib/mysql:rw
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db_data: