name: featch-test
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: fetchrewards
      MYSQL_DATABASE: fetch
      MYSQL_USER: fetch-be
      MYSQL_PASSWORD: fetch-be
    ports:
      - 3307:3306